version: "2"
checks:
  argument-count:
    enabled: false
  complex-logic:
    enabled: false
  file-lines:
    enabled: false
  method-complexity:
    enabled: false
  method-count:
    enabled: false
  method-lines:
    enabled: false
  nested-control-flow:
    enabled: false
  return-statements:
    enabled: false
  similar-code:
    enabled: false
  identical-code:
    enabled: false
plugins:
  gofmt:
    # Codeclimate go fmt does not agree with tip go fmt; consider re-enabling
    # CC when the advice matches up with tip again.
    enabled: false
  govet:
    enabled: true
  golint:
    enabled: true
exclude_paths:
  - vendor/
  - gps/_testdata
  - cmd/dep/testdata
  - testdata
  - gps/internal/pb
