engines:
  gofmt:
    enabled: true
  govet:
    enabled: true
  golint:
    enabled: true
ratings:
  paths:
    - "**.go"
exclude_paths:
  - vendor/
  - internal/gps/_testdata
  - cmd/dep/testdata
  - testdata
  - internal/gps/internal/pb
