memo = "31a7162c06758e4619ed89b91e1f48bf94ad14f394bbee79299ed0bb5150e409"

[[projects]]
  branch = "2.x"
  name = "github.com/Masterminds/semver"
  packages = ["."]
  revision = "94ad6eaf8457cf85a68c9b53fa42e9b1b8683783"

[[projects]]
  name = "github.com/Masterminds/vcs"
  packages = ["."]
  revision = "fbe9fb6ad5b5f35b3e82a7c21123cfc526cbf895"
  version = "v1.11.0"

[[projects]]
  branch = "master"
  name = "github.com/armon/go-radix"
  packages = ["."]
  revision = "4239b77079c7b5d1243b7b4736304ce8ddb6f0f2"

[[projects]]
  name = "github.com/pelletier/go-buffruneio"
  packages = ["."]
  revision = "c37440a7cf42ac63b919c752ca73a85067e05992"
  version = "v0.2.0"

[[projects]]
  branch = "master"
  name = "github.com/pelletier/go-toml"
  revision = "e32a2e04744250647a72bf17da1b09befc03b6b1"
  packages = ["."]

[[projects]]
  name = "github.com/pkg/errors"
  packages = ["."]
  revision = "645ef00459ed84a119197bfb8d8205042c6df63d"
  version = "v0.8.0"

[[projects]]
  name = "github.com/sdboyer/gps"
  packages = [".","internal","internal/fs","pkgtree"]
  revision = "b0f646b744e74543c094023d05339ffb82458e35"
  version = "v0.15.0"
