
[[dependencies]]
  branch = "2.x"
  name = "github.com/Masterminds/semver"

[[dependencies]]
  name = "github.com/Masterminds/vcs"
  version = "^1.8.0"

[[dependencies]]
  name = "github.com/pelletier/go-toml"
  revision = "fee7787d3f811af92276f5ff10107092e95b7a1d"

[[dependencies]]
  name = "github.com/pkg/errors"
  version = ">=0.8.0, <1.0.0"

[[dependencies]]
  name = "github.com/sdboyer/gps"
  version = ">=0.15.0, <1.0.0"
